### ISSUE TITLE
mp3 files do not work

### ISSUE THREAD

**Issue by evanmiltenburg** [jonatasgrosman/asrecognition#8]
Despite the example in the README using an mp3 file, it does not work on my Macbook:

```
>>> asr.transcribe(["/Users/emiel/Downloads/test.mp3"])
Traceback (most recent call last):
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/librosa/core/audio.py", line 149, in load
    with sf.SoundFile(path) as sf_desc:
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/Users/emiel/Downloads/test.mp3': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/asrecognition/engine.py", line 104, in transcribe
    data = data.map(_load_audio, num_proc=self.number_of_workers)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1665, in map
    return self._map_single(
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 185, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/datasets/fingerprint.py", line 397, in wrapper
    out = func(self, *args, **kwargs)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1997, in _map_single
    example = apply_function_on_filtered_inputs(example, i, offset=offset)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1906, in apply_function_on_filtered_inputs
    function(*fn_args, effective_indices, **fn_kwargs) if with_indices else function(*fn_args, **fn_kwargs)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/asrecognition/engine.py", line 99, in _load_audio
    waveform, sampling_rate = librosa.load(item["path"], sr=16_000)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/librosa/core/audio.py", line 166, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/librosa/core/audio.py", line 190, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/Users/emiel/miniconda3/lib/python3.8/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError
```

Wave files work fine. But it seems that just pip-installing ASRecognition is no guarantee for mp3-functionality.

**Comment by jonatasgrosman** [comment]
Hi @evanmiltenburg! Sorry for the very late reply. I had some health issues that forced me to stay offline for a while. My life is going back to normal slowly now...

You're right. Something is missing on the README. To handle mp3 files, you'll need to have an mp3 decoder installed on your machine too. For macOS machines, you can use this command `brew install ffmpeg` to install that decoder.

P.S.: The asrecognition tool is now deprecated in favor of https://github.com/jonatasgrosman/huggingsound

**Comment by evanmiltenburg** [comment]
Thanks for the update! No worries about the timing, GitHub is all just volunteer work anyway. (I just hope the issues that I’m filing are useful for others.)
